### ISSUE TITLE
Minor compilation error (fix)

### ISSUE THREAD

**Issue by jmkinzer** [xlgames-inc/XLE#8]
Have latest update VS2015... complains here:
Error	C3406	'typename': cannot be used in an elaborated type specifier	Utility	C:\XLE\Utility\Streams\Stream.cpp	237	

This:
`template<typename OutChar, typename InChar, typename typename std::enable_if<!CompatibleCharTypes<OutChar, InChar>::compatible>::type* = nullptr>`

Should be:
`template<typename OutChar, typename InChar, typename std::enable_if<!CompatibleCharTypes<OutChar, InChar>::compatible>::type* = nullptr>`

**Comment by djewsbury** [comment]
I've implemented the fix as suggested.
I'm using an older version of VS2015 -- but I'll update soon to check for any remaining errors.
